import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { AlertTriangle, ArrowUpRight, RadioTower } from "lucide-react";
import { CartesianGrid, Line, LineChart, XAxis, YAxis } from "recharts";

import { PageShell } from "@/components/page-shell";
import { Button } from "@/components/ui/button";
import { ChartContainer, ChartLegend, ChartLegendContent, ChartTooltip, ChartTooltipContent } from "@/components/ui/chart";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { ActiveFilters, FilterBar, MetricGrid, Panel, RiskLabel, SituationNav, SummaryBlock, type ActiveFilter } from "@/features/situasi/components";
import { issues, trend } from "@/features/situasi/data";

export const Route = createFileRoute("/situasi/risiko-prediksi")({head:()=>({meta:[{title:"Risiko & Prediksi — SPEKTRA"},{name:"description",content:"Prioritas risiko, early warning, dan proyeksi perkembangan isu berdasarkan pola saat ini."},{property:"og:title",content:"Risiko & Prediksi — SPEKTRA"},{property:"og:description",content:"Membaca risiko dan kemungkinan perkembangan isu."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}),component:RiskForecast});
const chartConfig={actual:{label:"Aktual",color:"var(--color-chart-1)"},forecast:{label:"Proyeksi",color:"var(--color-chart-3)"}};

function RiskForecast(){const [filters,setFilters]=useState<ActiveFilter[]>([]);const [range,setRange]=useState("7 Hari");const choose=(value:string)=>setFilters([{type:"issue",value}]);return <PageShell eyebrow="See · Anticipate" title="Risiko & Prediksi" description="Memprioritaskan isu berisiko dan membaca kemungkinan perkembangannya berdasarkan pola saat ini." actions={<FilterBar onAdvanced={()=>setFilters([{type:"risk",value:"Risiko Tinggi"}])}/>}>
  <SituationNav/><ActiveFilters filters={filters} remove={()=>setFilters([])} reset={()=>setFilters([])}/><div className="space-y-4">
    <MetricGrid items={[{value:"5",label:"Isu Risiko Tinggi",onClick:()=>setFilters([{type:"risk",value:"Risiko Tinggi"}])},{value:"3",label:"Risiko Meningkat"},{value:"7",label:"Early Warning Aktif"},{value:"4",label:"Isu Diprediksi Tumbuh"}]}/>
    <SummaryBlock title="Ringkasan Risiko" copy="Risiko tertinggi saat ini berasal dari perkembangan narasi terkait perluasan demonstrasi dan informasi tidak terverifikasi mengenai kericuhan. Keduanya menunjukkan peningkatan volume, perluasan wilayah, dan pertumbuhan aktor baru." highlights={["Demonstrasi Nasional berada pada risiko tinggi.","Dugaan serangan siber menunjukkan pertumbuhan 48%.","Terdapat 7 early warning aktif.","4 isu diprediksi meningkat dalam 7 hari ke depan."]}/>
    <Panel title="Isu Prioritas"><Table><TableHeader><TableRow><TableHead>Isu</TableHead><TableHead>Risiko</TableHead><TableHead>Volume</TableHead><TableHead>Growth</TableHead><TableHead>Wilayah</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{issues.slice(0,3).map((issue)=><TableRow key={issue.name} className="cursor-pointer" onClick={()=>choose(issue.name)}><TableCell className="font-medium">{issue.name}</TableCell><TableCell><RiskLabel value={issue.risk}/></TableCell><TableCell>{issue.volume}</TableCell><TableCell className="text-chart-2">{issue.growth}</TableCell><TableCell>{issue.region}</TableCell><TableCell>{issue.status}</TableCell></TableRow>)}</TableBody></Table></Panel>
    <div className="grid gap-4 xl:grid-cols-2"><Panel title="Matriks Risiko" description="Dampak × Kecepatan Penyebaran"><div className="grid h-80 grid-cols-2 grid-rows-2 gap-px overflow-hidden rounded-md bg-border"><div className="relative bg-destructive/8 p-3 text-[10px] text-muted-foreground">Dampak Tinggi / Penyebaran Rendah<Button variant="outline" size="sm" className="absolute bottom-[22%] left-[38%] h-7 border-chart-3 text-[10px]" onClick={()=>choose("Dugaan Serangan Siber")}>Serangan Siber</Button></div><div className="relative bg-destructive/12 p-3 text-[10px] text-muted-foreground">Dampak Tinggi / Penyebaran Tinggi<Button variant="destructive" size="sm" className="absolute left-[25%] top-[45%] h-7 text-[10px]" onClick={()=>choose("Demonstrasi Nasional")}>Demonstrasi Nasional</Button></div><div className="relative bg-card p-3 text-[10px] text-muted-foreground">Dampak Rendah / Penyebaran Rendah<Button variant="outline" size="sm" className="absolute right-[12%] top-[38%] h-7 text-[10px]" onClick={()=>choose("Gangguan Layanan Publik")}>Gangguan Layanan</Button></div><div className="bg-muted/20 p-3 text-[10px] text-muted-foreground">Dampak Rendah / Penyebaran Tinggi</div></div></Panel>
      <Panel title="Proyeksi Volume" action={<div className="flex gap-1">{["7 Hari","14 Hari","30 Hari"].map((item)=><Button key={item} size="sm" variant={range===item?"secondary":"ghost"} onClick={()=>setRange(item)}>{item}</Button>)}</div>}><ChartContainer config={chartConfig} className="h-64 w-full aspect-auto"><LineChart data={trend}><CartesianGrid vertical={false}/><XAxis dataKey="date"/><YAxis/><ChartTooltip content={<ChartTooltipContent/>}/><ChartLegend content={<ChartLegendContent/>}/><Line dataKey="actual" stroke="var(--color-actual)" strokeWidth={2}/><Line dataKey="forecast" stroke="var(--color-forecast)" strokeWidth={2} strokeDasharray="5 5"/></LineChart></ChartContainer><p className="mt-3 text-xs leading-5 text-muted-foreground">Volume percakapan diproyeksikan tetap tinggi dalam {range.toLowerCase()} ke depan dan berpotensi meningkat apabila muncul mobilisasi baru, berdasarkan pola saat ini.</p></Panel></div>
    <div className="grid gap-4 xl:grid-cols-[1fr_1.4fr]"><Panel title="Prediksi Penyebaran"><dl className="grid grid-cols-2 gap-4 text-xs">{[["Isu","Demonstrasi Nasional"],["Potensi Penyebaran","Tinggi"],["Platform Dominan","X, TikTok"],["Wilayah Berkembang","Bandung, Surabaya"],["Aktor Baru","+428 dalam 24 jam"]].map(([label,value])=><div key={label}><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>)}</dl></Panel><Panel title="Early Warning" action={<RadioTower className="size-4 text-destructive"/>}><div className="divide-y divide-border">{[["TINGGI","Lonjakan percakapan di Bandung","+86% dalam 3 jam"],["TINGGI","Narasi “aksi meluas” menyebar","Ke 3 platform baru"],["SEDANG","Peningkatan akun baru dalam cluster A","42 menit lalu"],["SEDANG","Sentimen negatif meningkat pada isu ekonomi","1 jam lalu"]].map(([level,title,meta])=><div key={title} className="flex items-start gap-3 py-3"><AlertTriangle className={level==="TINGGI"?"mt-0.5 size-4 text-destructive":"mt-0.5 size-4 text-chart-3"}/><div className="flex-1"><p className="text-xs font-medium">{title}</p><p className="mt-1 text-[10px] text-muted-foreground">{meta}</p></div><span className="text-[9px] font-semibold">{level}</span></div>)}</div></Panel></div>
    <Panel title="Pola Aktivitas Tidak Biasa" action={<Button variant="outline" size="sm">Lihat Detail<ArrowUpRight/></Button>}><p className="text-sm">37 akun menunjukkan pola waktu unggah yang berdekatan pada narasi yang sama dalam 2 jam terakhir.</p><p className="mt-2 text-xs text-muted-foreground">Terdapat indikasi pola aktivitas terkoordinasi yang memerlukan penelaahan lebih lanjut.</p></Panel>
    <Panel title="Detail Data Risiko"><Table><TableHeader><TableRow><TableHead>Isu</TableHead><TableHead>Risiko</TableHead><TableHead>Volume</TableHead><TableHead>Growth</TableHead><TableHead>Narasi Dominan</TableHead><TableHead>Aktor Dominan</TableHead><TableHead>Wilayah</TableHead><TableHead>Status</TableHead></TableRow></TableHeader><TableBody>{issues.map((issue,index)=><TableRow key={issue.name}><TableCell>{issue.name}</TableCell><TableCell><RiskLabel value={issue.risk}/></TableCell><TableCell>{issue.volume}</TableCell><TableCell>{issue.growth}</TableCell><TableCell>{index===0?"Aksi meluas":"Informasi tidak terverifikasi"}</TableCell><TableCell>{index===0?"@forum_mahasiswa":"@media_nusantara"}</TableCell><TableCell>{issue.region}</TableCell><TableCell>{issue.status}</TableCell></TableRow>)}</TableBody></Table></Panel>
  </div></PageShell>}