/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdministrasiRouteImport } from './routes/administrasi'
import { Route as AksiRouteImport } from './routes/aksi'
import { Route as ArsipRouteImport } from './routes/arsip'
import { Route as DampakRouteImport } from './routes/dampak'
import { Route as SituasiRouteImport } from './routes/situasi'
import { Route as StrategiRouteImport } from './routes/strategi'
import { Route as AksiIndexRouteImport } from './routes/aksi.index'
import { Route as AksiDistribusiNewsRouteImport } from './routes/aksi.distribusi-news'
import { Route as AksiDistribusiSosialRouteImport } from './routes/aksi.distribusi-sosial'
import { Route as AksiProduksiRouteImport } from './routes/aksi.produksi'
import { Route as SituasiIndexRouteImport } from './routes/situasi.index'
import { Route as SituasiSlugRouteImport } from './routes/situasi.$slug'
import { Route as StrategiIndexRouteImport } from './routes/strategi.index'
import { Route as StrategiSlugRouteImport } from './routes/strategi.$slug'
import { Route as SituasiSlugIndexRouteImport } from './routes/situasi.$slug.index'
import { Route as SituasiSlugEksplorasiRouteImport } from './routes/situasi.$slug.eksplorasi'
import { Route as SituasiSlugRisikoPrediksiRouteImport } from './routes/situasi.$slug.risiko-prediksi'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdministrasiRoute = AdministrasiRouteImport.update({
  id: '/administrasi',
  path: '/administrasi',
  getParentRoute: () => rootRouteImport,
} as any)
const AksiRoute = AksiRouteImport.update({
  id: '/aksi',
  path: '/aksi',
  getParentRoute: () => rootRouteImport,
} as any)
const ArsipRoute = ArsipRouteImport.update({
  id: '/arsip',
  path: '/arsip',
  getParentRoute: () => rootRouteImport,
} as any)
const DampakRoute = DampakRouteImport.update({
  id: '/dampak',
  path: '/dampak',
  getParentRoute: () => rootRouteImport,
} as any)
const SituasiRoute = SituasiRouteImport.update({
  id: '/situasi',
  path: '/situasi',
  getParentRoute: () => rootRouteImport,
} as any)
const StrategiRoute = StrategiRouteImport.update({
  id: '/strategi',
  path: '/strategi',
  getParentRoute: () => rootRouteImport,
} as any)
const AksiIndexRoute = AksiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AksiRoute,
} as any)
const AksiDistribusiNewsRoute = AksiDistribusiNewsRouteImport.update({
  id: '/distribusi-news',
  path: '/distribusi-news',
  getParentRoute: () => AksiRoute,
} as any)
const AksiDistribusiSosialRoute = AksiDistribusiSosialRouteImport.update({
  id: '/distribusi-sosial',
  path: '/distribusi-sosial',
  getParentRoute: () => AksiRoute,
} as any)
const AksiProduksiRoute = AksiProduksiRouteImport.update({
  id: '/produksi',
  path: '/produksi',
  getParentRoute: () => AksiRoute,
} as any)
const SituasiIndexRoute = SituasiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SituasiRoute,
} as any)
const SituasiSlugRoute = SituasiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SituasiRoute,
} as any)
const StrategiIndexRoute = StrategiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StrategiRoute,
} as any)
const StrategiSlugRoute = StrategiSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => StrategiRoute,
} as any)
const SituasiSlugIndexRoute = SituasiSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SituasiSlugRoute,
} as any)
const SituasiSlugEksplorasiRoute = SituasiSlugEksplorasiRouteImport.update({
  id: '/eksplorasi',
  path: '/eksplorasi',
  getParentRoute: () => SituasiSlugRoute,
} as any)
const SituasiSlugRisikoPrediksiRoute =
  SituasiSlugRisikoPrediksiRouteImport.update({
    id: '/risiko-prediksi',
    path: '/risiko-prediksi',
    getParentRoute: () => SituasiSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/administrasi': typeof AdministrasiRoute
  '/aksi': typeof AksiRouteWithChildren
  '/arsip': typeof ArsipRoute
  '/dampak': typeof DampakRoute
  '/situasi': typeof SituasiRouteWithChildren
  '/strategi': typeof StrategiRouteWithChildren
  '/aksi/distribusi-news': typeof AksiDistribusiNewsRoute
  '/aksi/distribusi-sosial': typeof AksiDistribusiSosialRoute
  '/aksi/produksi': typeof AksiProduksiRoute
  '/situasi/$slug': typeof SituasiSlugRouteWithChildren
  '/strategi/$slug': typeof StrategiSlugRoute
  '/aksi/': typeof AksiIndexRoute
  '/situasi/': typeof SituasiIndexRoute
  '/strategi/': typeof StrategiIndexRoute
  '/situasi/$slug/eksplorasi': typeof SituasiSlugEksplorasiRoute
  '/situasi/$slug/risiko-prediksi': typeof SituasiSlugRisikoPrediksiRoute
  '/situasi/$slug/': typeof SituasiSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/administrasi': typeof AdministrasiRoute
  '/arsip': typeof ArsipRoute
  '/dampak': typeof DampakRoute
  '/aksi/distribusi-news': typeof AksiDistribusiNewsRoute
  '/aksi/distribusi-sosial': typeof AksiDistribusiSosialRoute
  '/aksi/produksi': typeof AksiProduksiRoute
  '/strategi/$slug': typeof StrategiSlugRoute
  '/aksi': typeof AksiIndexRoute
  '/situasi': typeof SituasiIndexRoute
  '/strategi': typeof StrategiIndexRoute
  '/situasi/$slug/eksplorasi': typeof SituasiSlugEksplorasiRoute
  '/situasi/$slug/risiko-prediksi': typeof SituasiSlugRisikoPrediksiRoute
  '/situasi/$slug': typeof SituasiSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/administrasi': typeof AdministrasiRoute
  '/aksi': typeof AksiRouteWithChildren
  '/arsip': typeof ArsipRoute
  '/dampak': typeof DampakRoute
  '/situasi': typeof SituasiRouteWithChildren
  '/strategi': typeof StrategiRouteWithChildren
  '/aksi/distribusi-news': typeof AksiDistribusiNewsRoute
  '/aksi/distribusi-sosial': typeof AksiDistribusiSosialRoute
  '/aksi/produksi': typeof AksiProduksiRoute
  '/situasi/$slug': typeof SituasiSlugRouteWithChildren
  '/strategi/$slug': typeof StrategiSlugRoute
  '/aksi/': typeof AksiIndexRoute
  '/situasi/': typeof SituasiIndexRoute
  '/strategi/': typeof StrategiIndexRoute
  '/situasi/$slug/eksplorasi': typeof SituasiSlugEksplorasiRoute
  '/situasi/$slug/risiko-prediksi': typeof SituasiSlugRisikoPrediksiRoute
  '/situasi/$slug/': typeof SituasiSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/administrasi'
    | '/aksi'
    | '/arsip'
    | '/dampak'
    | '/situasi'
    | '/strategi'
    | '/aksi/distribusi-news'
    | '/aksi/distribusi-sosial'
    | '/aksi/produksi'
    | '/situasi/$slug'
    | '/strategi/$slug'
    | '/aksi/'
    | '/situasi/'
    | '/strategi/'
    | '/situasi/$slug/eksplorasi'
    | '/situasi/$slug/risiko-prediksi'
    | '/situasi/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/administrasi'
    | '/arsip'
    | '/dampak'
    | '/aksi/distribusi-news'
    | '/aksi/distribusi-sosial'
    | '/aksi/produksi'
    | '/strategi/$slug'
    | '/aksi'
    | '/situasi'
    | '/strategi'
    | '/situasi/$slug/eksplorasi'
    | '/situasi/$slug/risiko-prediksi'
    | '/situasi/$slug'
  id:
    | '__root__'
    | '/'
    | '/administrasi'
    | '/aksi'
    | '/arsip'
    | '/dampak'
    | '/situasi'
    | '/strategi'
    | '/aksi/distribusi-news'
    | '/aksi/distribusi-sosial'
    | '/aksi/produksi'
    | '/situasi/$slug'
    | '/strategi/$slug'
    | '/aksi/'
    | '/situasi/'
    | '/strategi/'
    | '/situasi/$slug/eksplorasi'
    | '/situasi/$slug/risiko-prediksi'
    | '/situasi/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdministrasiRoute: typeof AdministrasiRoute
  AksiRoute: typeof AksiRouteWithChildren
  ArsipRoute: typeof ArsipRoute
  DampakRoute: typeof DampakRoute
  SituasiRoute: typeof SituasiRouteWithChildren
  StrategiRoute: typeof StrategiRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/administrasi': {
      id: '/administrasi'
      path: '/administrasi'
      fullPath: '/administrasi'
      preLoaderRoute: typeof AdministrasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aksi': {
      id: '/aksi'
      path: '/aksi'
      fullPath: '/aksi'
      preLoaderRoute: typeof AksiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arsip': {
      id: '/arsip'
      path: '/arsip'
      fullPath: '/arsip'
      preLoaderRoute: typeof ArsipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dampak': {
      id: '/dampak'
      path: '/dampak'
      fullPath: '/dampak'
      preLoaderRoute: typeof DampakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/situasi': {
      id: '/situasi'
      path: '/situasi'
      fullPath: '/situasi'
      preLoaderRoute: typeof SituasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/strategi': {
      id: '/strategi'
      path: '/strategi'
      fullPath: '/strategi'
      preLoaderRoute: typeof StrategiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aksi/': {
      id: '/aksi/'
      path: '/'
      fullPath: '/aksi/'
      preLoaderRoute: typeof AksiIndexRouteImport
      parentRoute: typeof AksiRoute
    }
    '/aksi/distribusi-news': {
      id: '/aksi/distribusi-news'
      path: '/distribusi-news'
      fullPath: '/aksi/distribusi-news'
      preLoaderRoute: typeof AksiDistribusiNewsRouteImport
      parentRoute: typeof AksiRoute
    }
    '/aksi/distribusi-sosial': {
      id: '/aksi/distribusi-sosial'
      path: '/distribusi-sosial'
      fullPath: '/aksi/distribusi-sosial'
      preLoaderRoute: typeof AksiDistribusiSosialRouteImport
      parentRoute: typeof AksiRoute
    }
    '/aksi/produksi': {
      id: '/aksi/produksi'
      path: '/produksi'
      fullPath: '/aksi/produksi'
      preLoaderRoute: typeof AksiProduksiRouteImport
      parentRoute: typeof AksiRoute
    }
    '/situasi/': {
      id: '/situasi/'
      path: '/'
      fullPath: '/situasi/'
      preLoaderRoute: typeof SituasiIndexRouteImport
      parentRoute: typeof SituasiRoute
    }
    '/situasi/$slug': {
      id: '/situasi/$slug'
      path: '/$slug'
      fullPath: '/situasi/$slug'
      preLoaderRoute: typeof SituasiSlugRouteImport
      parentRoute: typeof SituasiRoute
    }
    '/strategi/': {
      id: '/strategi/'
      path: '/'
      fullPath: '/strategi/'
      preLoaderRoute: typeof StrategiIndexRouteImport
      parentRoute: typeof StrategiRoute
    }
    '/strategi/$slug': {
      id: '/strategi/$slug'
      path: '/$slug'
      fullPath: '/strategi/$slug'
      preLoaderRoute: typeof StrategiSlugRouteImport
      parentRoute: typeof StrategiRoute
    }
    '/situasi/$slug/': {
      id: '/situasi/$slug/'
      path: '/'
      fullPath: '/situasi/$slug/'
      preLoaderRoute: typeof SituasiSlugIndexRouteImport
      parentRoute: typeof SituasiSlugRoute
    }
    '/situasi/$slug/eksplorasi': {
      id: '/situasi/$slug/eksplorasi'
      path: '/eksplorasi'
      fullPath: '/situasi/$slug/eksplorasi'
      preLoaderRoute: typeof SituasiSlugEksplorasiRouteImport
      parentRoute: typeof SituasiSlugRoute
    }
    '/situasi/$slug/risiko-prediksi': {
      id: '/situasi/$slug/risiko-prediksi'
      path: '/risiko-prediksi'
      fullPath: '/situasi/$slug/risiko-prediksi'
      preLoaderRoute: typeof SituasiSlugRisikoPrediksiRouteImport
      parentRoute: typeof SituasiSlugRoute
    }
  }
}

interface AksiRouteChildren {
  AksiDistribusiNewsRoute: typeof AksiDistribusiNewsRoute
  AksiDistribusiSosialRoute: typeof AksiDistribusiSosialRoute
  AksiProduksiRoute: typeof AksiProduksiRoute
  AksiIndexRoute: typeof AksiIndexRoute
}

const AksiRouteChildren: AksiRouteChildren = {
  AksiDistribusiNewsRoute: AksiDistribusiNewsRoute,
  AksiDistribusiSosialRoute: AksiDistribusiSosialRoute,
  AksiProduksiRoute: AksiProduksiRoute,
  AksiIndexRoute: AksiIndexRoute,
}

const AksiRouteWithChildren = AksiRoute._addFileChildren(AksiRouteChildren)

interface SituasiSlugRouteChildren {
  SituasiSlugEksplorasiRoute: typeof SituasiSlugEksplorasiRoute
  SituasiSlugRisikoPrediksiRoute: typeof SituasiSlugRisikoPrediksiRoute
  SituasiSlugIndexRoute: typeof SituasiSlugIndexRoute
}

const SituasiSlugRouteChildren: SituasiSlugRouteChildren = {
  SituasiSlugEksplorasiRoute: SituasiSlugEksplorasiRoute,
  SituasiSlugRisikoPrediksiRoute: SituasiSlugRisikoPrediksiRoute,
  SituasiSlugIndexRoute: SituasiSlugIndexRoute,
}

const SituasiSlugRouteWithChildren = SituasiSlugRoute._addFileChildren(
  SituasiSlugRouteChildren,
)

interface SituasiRouteChildren {
  SituasiSlugRoute: typeof SituasiSlugRouteWithChildren
  SituasiIndexRoute: typeof SituasiIndexRoute
}

const SituasiRouteChildren: SituasiRouteChildren = {
  SituasiSlugRoute: SituasiSlugRouteWithChildren,
  SituasiIndexRoute: SituasiIndexRoute,
}

const SituasiRouteWithChildren =
  SituasiRoute._addFileChildren(SituasiRouteChildren)

interface StrategiRouteChildren {
  StrategiSlugRoute: typeof StrategiSlugRoute
  StrategiIndexRoute: typeof StrategiIndexRoute
}

const StrategiRouteChildren: StrategiRouteChildren = {
  StrategiSlugRoute: StrategiSlugRoute,
  StrategiIndexRoute: StrategiIndexRoute,
}

const StrategiRouteWithChildren = StrategiRoute._addFileChildren(
  StrategiRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdministrasiRoute: AdministrasiRoute,
  AksiRoute: AksiRouteWithChildren,
  ArsipRoute: ArsipRoute,
  DampakRoute: DampakRoute,
  SituasiRoute: SituasiRouteWithChildren,
  StrategiRoute: StrategiRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
